-- Snapshot only. Authoritative source is initDb() in server.js.
-- Reverb deliberately holds no copy of SMS/email/calendar data — every
-- tool call fetches live from text-cmd / Lifecmd2 at query time.

CREATE TABLE IF NOT EXISTS settings (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL              -- 'owner_pin_hash' lives here
);

CREATE TABLE IF NOT EXISTS conversations (
  id         SERIAL PRIMARY KEY,
  title      TEXT NOT NULL DEFAULT 'New chat',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS chat_messages (
  id              SERIAL PRIMARY KEY,
  conversation_id INTEGER REFERENCES conversations(id) ON DELETE CASCADE,
  role            TEXT NOT NULL,
  content         TEXT NOT NULL,
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- task_id is a content hash (kind|from|snippet), not a DB-assigned id — the
-- sweep task list is regenerated by the model each run, so persistence keys
-- off the source content instead of a stable row.
CREATE TABLE IF NOT EXISTS swept_done (
  task_id    TEXT PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- tier is nullable: NULL means no manual override, in which case importance
-- is derived from seen/replied/dismissed counts + rule hits at read time
-- (see src/lib/contacts.js). A user-set tier ('vip'|'normal'|'muted') always
-- wins over the derived score.
CREATE TABLE IF NOT EXISTS contacts (
  id               SERIAL PRIMARY KEY,
  kind             TEXT NOT NULL,        -- sms|email|bizemail|whatsapp|messenger|instagram|job
  identifier       TEXT NOT NULL,        -- normalized email/phone/handle
  display_name     TEXT,
  tier             TEXT,
  seen_count       INTEGER NOT NULL DEFAULT 0,
  replied_count    INTEGER NOT NULL DEFAULT 0,
  dismissed_count  INTEGER NOT NULL DEFAULT 0,
  last_seen_at     TIMESTAMPTZ,
  UNIQUE (kind, identifier)
);
